config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    scope module: 'event' do
      resources :boardgames, only: [:index, :show, :update, :destroy]
      get "/players/show_by_dni", to: "players#show_by_dni"
      resources :players, except: [:new, :destroy]
      resources :loans, only: [:index, :create, :destroy]

      resources :tournaments, except: [:new] do
        resources :participants, only: [:create, :destroy, :update]
        get :autocomplete_boardgame_name, on: :collection
        get :autocomplete_player_dni, on: :collection
      end
    end
  end

  namespace :admin do
    resources :boardgames
    resources :organizations
    resources :players
    resources :users

    namespace :import do
      resources :bgg_boardgames, only: [:index, :create, :new]
      resources :bgg_collections, only: [:index, :create]
    end
  end

  # defaults to dashboard
  root to: redirect('/events')
end

app/models/player.rb
class Player < ApplicationRecord
  include SoftDeletable

  has_and_belongs_to_many :events
  has_and_belongs_to_many :organizations, -> { distinct }
  has_many :loans
  has_many :participants

  validates_presence_of :firstname, :lastname
  validates_size_of :phone, is: 9
  validates :dni, spanish_vat: true, presence: true,
                  uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  after_destroy :remove_future_participants
  before_save { self.dni = dni.upcase }

  def name
    "#{firstname} #{lastname}"
  end

  def dni_plus_name
    "#{dni} | #{name}"
  end

  def age
    return '' unless birthday
    today = Date.today
    had_birthday = today.month > birthday.month || (today.month == birthday.month && today.day >= birthday.day) ? true : false
    today.year - birthday.year - (had_birthday ? 0 : 1)
  end

  def active_loans
    loans.where(returned_at: nil)
  end

  private

  def remove_future_participants
    return false unless participants.present?
    participants.each do |participant|
      participant.destroy if participant.at_future_tournament?
    end
  end
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  def index
    @players = current_players.page(params[:page])
  end

  def show
    @player = current_players.find_by(id: params[:id])
  end

  def new
    @player = Player.new
  end

  def edit
    @player = current_players.find_by(id: params[:id])
  end

  def create
    @player = Player.new(player_params)
    @player.organization = current_organization
    if @player.save
      redirect_to admin_player_url(@player), notice: "Player was successfully created."
    else
      render :new
    end
  end

  def update
    @player = current_players.find_by(id: params[:id])
    if @player.update(player_params)
      redirect_to admin_player_url(@player), notice: "Player was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @player = current_players.find_by(id: params[:id])
    if @player.destroy
      redirect_to admin_players_path, notice: "Player was successfully removed."
    else
      redirect_to admin_players_path, alert: @player.errors[:destroy].to_sentence
    end
  end

  private

  def player_params
    params.require(:player).permit(:dni, :firstname, :lastname, :city, :province, :birthday, :email, :phone)
  end

  def current_organization
    current_user.organization
  end

  def current_players
    current_organization.players
  end
end

app/controllers/event/players_controller.rb
class Event::PlayersController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event
  before_action :set_organization, only: [:show_by_dni, :create, :update]

  def index
    @players = @event.players.all
    @player  = @event.players.new
  end

  def show
    @player = @event.players.find_by(id: params[:id])
  end

  def show_by_dni
    player = @organization.players.find_by(dni: params[:dni].upcase)
    unless player
      render json: { error: "player not found" },
             status: 404
      return
    end
    render json: player
  end

  def edit
    @player = @event.players.find_by(id: params[:id])
  end

  def create
    @players = @event.players.all
    @player  = @event.players.new(player_params)
    @player.organizations.push(@organization)
    if @event.save
      redirect_to [@event, @player], notice: "User was successfully created."
    else
      render :index
    end
  end

  def update
    @player = @event.players.find_by(id: params[:id])
    unless @player
      @player = @organization.players.find_by(id: params[:id])
      @event.players.push(@player)
    end

    if @player.update(player_params)
      redirect_to [@event, @player], notice: "User was successfully included."
    else
      render :edit
    end
  end

  private

  def player_params
    params.require(:player).permit(:dni, :firstname, :lastname, :city, :province, :birthday, :email, :phone)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def set_organization
    @organization = @event.organization
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/admin/players/_form.html.erb
<div class="col-sm-12">
  <!-- START panel-->
  <div class="panel panel-default">
    <div class="panel-body">

      <%= form_for([:admin, @player], html: {class: "form-horizontal"}) do |f| %>
      <% if @player.errors.any? %>
        <div class="alert bg-danger-light alert-dismissible fade in">
          <button type="button" data-dismiss="alert" aria-label="Close" class="close">
            <span aria-hidden="true">×</span>
          </button>
          <div id="error_explanation">
            <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

            <ul>
              <% @player.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :dni, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :dni, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :nombre, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :firstname, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :apellidos, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :lastname, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :ciudad, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :city, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :provincia, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :province, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :cumpleaños, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.date_select :birthday, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :email, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :teléfono, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.number_field :phone, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">

          <%= f.button "Guardar cambios", {class: "btn btn-lg btn-primary"} %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/players/_pagination_footer.html.erb
<div class="panel-footer">
   <div class="row">
      <div class="col-lg-6 col-lg-offset-6 text-right">
      	<%= paginate elements %>
      </div>
   </div>
</div>

app/views/admin/players/edit.html.erb
<div class="content-heading">
	Editar <%= @player.name %>
   <%= link_to 'Volver', :back, { class: "mb-lg btn btn-default btn-lg pull-right" } %>
</div>
<div class="row">
	<%= render 'form' %>
</div>

app/views/admin/players/index.html.erb
<div class="content-heading">
   Jugadores
   <%= link_to 'Volver', :back, { class: "mb-lg btn btn-default btn-lg pull-right" } %>
</div>
<div class="row">
   <div class="col-sm-12">
      <div class="panel">
         <div class="panel-heading"></div>
         <div class="table-responsive">
            <table class="table table-bordered table-hover">
               <thead>
                  <tr>
                     <th>#</th>
                     <th>DNI</th>
                     <th>Nombre</th>
                     <th>Ciudad</th>
                     <th>Provincia</th>
                     <th>Edad</th>
                     <th></th>
                  </tr>
               </thead>
               <tbody>

                  <% @players.each_with_index do |player, index| %>
                  <tr>
                     <td><%= index+1 %></td>
                     <td><%= player[:dni] %></td>
                     <td><%= player.name %></td>
                     <td><%= player[:city] %></td>
                     <td><%= player[:province] %></td>
                     <td><%= player.age %></td>
                     <td>
                        <%= link_to 'Mostrar', admin_player_path(player), { class: "btn btn-sm bt-primary bg-gray-lighter" } %>
                        <%= link_to '', edit_admin_player_path(player), { class: "btn btn-success btn-sm bg-success-light fa fa-pencil" } %>
                        <%= link_to '', admin_player_path(player), { method: :delete, class: "btn btn-danger btn-sm bg-danger-light fa fa-trash-o" } %>
                        </td>
                  </tr>
                  <% end %>

               </tbody>
            </table>
         </div>
         <%= render partial: 'pagination_footer', locals: { elements: @players } %>  
      </div>
   </div>
</div>

app/views/admin/players/new.html.erb
<div class="content-heading">
	Nuevo jugador
</div>
<div class="row">
	<%= render 'form' %>
</div>