config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    scope module: 'event' do
      resources :boardgames, only: [:index, :show, :update, :destroy]
      get "/players/show_by_dni", to: "players#show_by_dni"
      resources :players, except: [:new, :destroy]
      resources :loans, only: [:index, :create, :destroy]

      resources :tournaments, except: [:new] do
        resources :participants, only: [:create, :destroy, :update]
        get :autocomplete_boardgame_name, on: :collection
        get :autocomplete_player_dni, on: :collection
      end
    end
  end

  namespace :admin do
    resources :boardgames
    resources :organizations
    resources :players
    resources :users

    namespace :import do
      resources :bgg_boardgames, only: [:index, :create, :new]
      resources :bgg_collections, only: [:index, :create]
    end
  end

  # defaults to dashboard
  root to: redirect('/events')
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :boardgames, -> { distinct },
                          before_add: :cant_add_boardgame_with_active_loans,
                          before_remove: :cant_del_boardgame_with_active_loans
  has_and_belongs_to_many :players, -> { distinct }
  has_many :loans
  has_many :tournaments
  belongs_to :organization

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :organization, presence: true
  validate  :start_date_cannot_be_after_end_date

  private

  def start_date_cannot_be_after_end_date
    return unless start_date.present? && end_date.present?
    errors.add(:start_date, "can't be after end_date") if start_date > end_date
  end

  def cant_add_boardgame_with_active_loans(boardgame)
    return if boardgame.active_loans.blank?
    errors.add(:boardgame, "boardgame with active loans can't be added")
    raise ActiveRecord::Rollback
  end

  def cant_del_boardgame_with_active_loans(boardgame)
    return unless boardgame.active_loans.at_event(self)
    errors.add(:boardgame, "boardgame with active loans can't be removed")
    raise ActiveRecord::Rollback
  end
end

app/controllers/concerns/events/check_authorized.rb
module Events
  module CheckAuthorized
    extend ActiveSupport::Concern

    included do
      before_action :current_user_belongs_to_organization

      def event_organization
        @event = Event.find(params[:event_id])
        @event.organization
      end

      def current_user_belongs_to_organization
        unless event_organization == current_user.organization || current_user.admin?
          redirect_to root_path, notice: "Access forbidden."
        end
      end
    end
  end
end

app/controllers/event/boardgames_controller.rb
class Event::BoardgamesController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event, :set_organization_boardgames

  def index
    @boardgames_included     = @event.boardgames.order(name: :asc).to_a
    @boardgames_not_included = @boardgames.where.not(id: @boardgames_included).order(name: :asc)
  end

  def show
    @boardgame = @event.boardgames.find_by(id: params[:id])
    @loan      = @boardgame.active_loans.at_event(@event)

    if @loan.present?
      loan_json = {
        id:  @loan[0].id,
        dni: @loan[0].player.dni,
        name: @loan[0].player.name
      }
    end

    respond_to do |format|
      format.html
      format.json do
        render json: {
          attributes: @boardgame,
          loan:       loan_json
        }
      end
    end
  end

  def update
    @boardgame = @boardgames.find_by(id: params[:id])

    if @event.boardgames << @boardgame
      redirect_to event_boardgames_path, notice: "Juego añadido al evento."
    else
      redirect_to event_boardgames_path, alert: @event.errors[:boardgame].to_sentence
    end
  end

  def destroy
    @boardgame = @boardgames.find_by(id: params[:id])
    if @event.boardgames.delete(@boardgame)
      redirect_to event_boardgames_path, notice: "Juego eliminado del evento."
    else
      redirect_to event_boardgames_path, alert: @event.errors[:boardgame].to_sentence
    end
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def set_organization_boardgames
    @boardgames = @event.organization.boardgames
  end
end

app/controllers/event/loans_controller.rb
class Event::LoansController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event

  def index
    @loan  = Loan.new
    @loans = @event.loans.ordered
    keywords = params.fetch(:search, {}).fetch(:keywords, nil)
    @boardgames = search_boardgame_to_borrow_by_keyword(keywords)
  end

  def create
    player = @event.players.find_by(dni: params[:dni])

    if player
      @loan = @event.loans.new(boardgame_id: params[:loan][:boardgame_id], player: player)

      if @loan.save
        redirect_to event_loans_url(@event), notice: 'Loan was successfully created.'
      else
        redirect_to event_loans_url(@event), alert: 'Sorry, loans fails to start.'
      end
    else
      redirect_to event_loans_url(@event), alert: 'Invalid DNI, loans fails to start.'
    end
  end

  def destroy
    @loan = @event.loans.find_by(id: params[:id])

    if @loan.return
      redirect_to event_loans_url(@event), notice: 'Loan was successfully returned.'
    else
      redirect_to event_loans_url(@event), alert: 'Loan fails to return.'
    end
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def search_boardgame_to_borrow_by_keyword(keyword)
    return [] unless keyword.present?

    if keyword.length == 13 && keyword.match(/^\d+$/)
      @event.boardgames.search_by_barcode(keyword)
    elsif keyword.length == 5 && keyword.match(/^[a-zA-Z]{2}\d{3}/)
      @event.boardgames.search_by_internalcode(keyword)
    else
      @event.boardgames.search_by_name(keyword)
    end
  end
end

app/controllers/event/participants_controller.rb
class Event::ParticipantsController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event, :find_tournament

  def create
    player = @event.players.find_by(id: params[:search][:player_id])
    if player
      @participant = @tournament.participants.new(player: player)
      if @participant.save
        flash[:notice] = 'Jugador añadido al torneo.'
      else
        flash[:alert] = @participant.errors.values
      end
    else
      flash[:alert] = 'DNI no válido, no se pudo añadir al jugador al torneo.'
    end

    redirect_to event_tournament_path(@event, @tournament)
  end

  def destroy
    @participant = @tournament.participants.find_by(id: params[:id])

    if @participant.destroy
      flash[:notice] = 'Jugador eliminado del torneo.'
    else
      flash[:alert] = @participant.errors[:participant].to_sentence
    end

    redirect_to event_tournament_path(@event, @tournament)
  end

  def update
    @participant = @tournament.participants.find_by(id: params[:id])
    @participant.toggle_confirmed
    @participant.save

    redirect_to event_tournament_path(@event, @tournament), notice: 'Jugador confirmado.'
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_tournament
    @tournament = @event.tournaments.find_by(id: params[:tournament_id])
  end
end

app/controllers/event/players_controller.rb
class Event::PlayersController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event
  before_action :set_organization, only: [:show_by_dni, :create, :update]

  def index
    @players = @event.players.all
    @player  = @event.players.new
  end

  def show
    @player = @event.players.find_by(id: params[:id])
  end

  def show_by_dni
    player = @organization.players.find_by(dni: params[:dni].upcase)
    unless player
      render json: { error: "player not found" },
             status: 404
      return
    end
    render json: player
  end

  def edit
    @player = @event.players.find_by(id: params[:id])
  end

  def create
    @players = @event.players.all
    @player  = @event.players.new(player_params)
    @player.organizations.push(@organization)
    if @event.save
      redirect_to [@event, @player], notice: "User was successfully created."
    else
      render :index
    end
  end

  def update
    @player = @event.players.find_by(id: params[:id])
    unless @player
      @player = @organization.players.find_by(id: params[:id])
      @event.players.push(@player)
    end

    if @player.update(player_params)
      redirect_to [@event, @player], notice: "User was successfully included."
    else
      render :edit
    end
  end

  private

  def player_params
    params.require(:player).permit(:dni, :firstname, :lastname, :city, :province, :birthday, :email, :phone)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def set_organization
    @organization = @event.organization
  end
end

app/controllers/event/tournaments_controller.rb
class Event::TournamentsController < ApplicationController
  include Events::CheckAuthorized

  autocomplete :boardgame, :name, full: true, limit: 20, extra_data: [:thumbnail]
  autocomplete :player, :dni, limit: 20, extra_data: [:firstname, :lastname], display_value: :dni_plus_name
  before_action :find_event

  def index
    @tournaments = @event.tournaments.all
    @tournament  = @event.tournaments.new
  end

  def show
    @tournament    = @event.tournaments.find_by(id: params[:id])
    @boardgame     = @tournament.boardgame
    @competitors   = @tournament.competitors
    @substitutes   = @tournament.substitutes
    @confirmed     = @tournament.confirmed
    @league_rounds = @tournament.league_system(@confirmed) if @confirmed.present?
  end

  def create
    @tournaments = @event.tournaments.all
    @tournament  = @event.tournaments.new(tournament_params)

    if @event.save
      redirect_to [@event, @tournament], notice: 'Tournament was successfully created.'
    else
      render :index, alert: 'Sorry, tournament wasnt created.'
    end
  end

  def edit
    @tournament = @event.tournaments.find_by(id: params[:id])
  end

  def update
    @tournament = @event.tournaments.find_by(id: params[:id])

    if @tournament.update(tournament_params)
      redirect_to [@event, @tournament], notice: 'Tournament was successfully updated.'
    else
      render :edit
    end
  end

  private

  def get_autocomplete_items(parameters)
    items = active_record_get_autocomplete_items(parameters)

    if    parameters[:model] == Boardgame then @event.boardgames & items
    elsif parameters[:model] == Player    then @event.players & items
    end
  end

  def tournament_params
    params.require(:tournament).permit(:name, :max_competitors, :max_substitutes, :date, :minage, :boardgame_id, :event)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_organization
  before_action :current_user_is_the_owner, only: [:show, :edit, :update, :destroy]

  def index
    @events = current_user.admin? ? Event.all : @organization.events
  end

  def show
    @event             = Event.find_by(id: params[:id])
    @loans_count       = @event.loans.count
    @boardgames_count  = @event.boardgames.count
    @players_count     = @event.players.count
    @tournaments_count = @event.tournaments.count
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find_by(id: params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.organization = @organization
    if @event.save
      redirect_to @event, notice: "Event was successfully created."
    else
      render :new
    end
  end

  def update
    @event = Event.find_by(id: params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find_by(id: params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :city, :province)
  end

  def set_organization
    @organization = current_user.organization
  end

  def current_user_is_the_owner
    @event = Event.find_by(id: params[:id])
    unless @event.organization == current_user.organization || current_user.admin?
      redirect_to root_path, notice: "Acess forbidden"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="col-sm-12">
  <!-- START panel-->
  <div class="panel panel-default">
    <div class="panel-body">

      <%= form_for(@event, html: {class: "form-horizontal"}) do |f| %>
      <% if @event.errors.any? %>
        <div class="alert bg-danger-light alert-dismissible fade in">
          <button type="button" data-dismiss="alert" aria-label="Close" class="close">
            <span aria-hidden="true">×</span>
          </button>
          <div id="error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
              <% @event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :nombre, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :name, {class: "form-control"} %>  
        </div>
      </div>

      <div class="row">
      <%= f.label :fecha, {class: "col-lg-2 control-label"} %>
      <div class="col-lg-10">
        <div class="col-lg-6">
          <div class="form-group">
            <div >
              <%= f.datetime_select :start_date, {class: "form-control"} %>  
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="form-group">
            <div>
              <%= f.datetime_select :end_date, {class: "form-control"} %>  
            </div>
          </div>
        </div>
      </div>
      </div>

      <div class="form-group">
        <%= f.label :ciudad, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :city, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :provincia, {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10">
          <%= f.text_field :province, {class: "form-control"} %>  
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">

          <%= f.button "Guardar cambios", {class: "btn btn-lg btn-primary"} %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="content-heading">
	Editar <%= @event.name %>
   <%= link_to 'Volver', events_path(@event), { class: "mb-lg btn btn-default btn-lg pull-right" } %>
</div>
<div class="row">
	<%= render 'form' %>
</div>

app/views/events/index.html.slim
.content-heading
	| Eventos
.row
	.col-sm-12
		.panel
			.panel-heading
			.table-responsive
				table.table.table-bordered.table-hover
					thead
						tr
							th #
							th Nombre
							th Comienza
							th Finaliza
							th Ciudad
							th Provincia
							- if current_user.admin?
								th Organizatión
							th
					tbody
						- @events.each_with_index do |event, index|
							tr
								td= index + 1
								td= event[:name]
								td= beauty_date(event[:start_date])
								td= beauty_date(event[:end_date])
								td= event[:city]
								td= event[:province]
								- if current_user.admin?
									td= event.organization.name 
								td
									= link_to 'Mostrar', event_path(event), { class: "btn btn-default btn-sm bg-gray-lighter" }
									= link_to '', edit_event_path(event), { class: "btn btn-success btn-sm bg-success-light fa fa-pencil" }

app/views/events/new.html.erb
<div class="content-heading">
	Nuevo Evento
</div>
<div class="row">
	<%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="content-heading">
	<%= @event.name %>
   <%= link_to 'Volver', events_path(@event), { class: "mb-lg btn btn-default btn-lg pull-right" } %>
</div>

<div class="row">
   <div class="col-lg-3 col-md-6">
      <!-- START panel-->
      <div class="panel panel-green">
         <div class="panel-heading">
            <div class="row">
               <div class="col-xs-3">
                  <em class="fa fa-users fa-5x"></em>
               </div>
               <div class="col-xs-9 text-right">
                  <div class="text-lg"><%= @players_count %></div>
                  <p class="m0">Jugadores</p>
               </div>
            </div>
         </div>
         <a href=<%= event_players_path(@event) %> class="panel-footer bg-gray-dark bt0 clearfix btn-block">
            <span class="pull-left">Entrar</span>
            <span class="pull-right">
               <em class="fa fa-chevron-circle-right"></em>
            </span>
         </a>
         <!-- END panel-->
      </div>
   </div>
   <div class="col-lg-3 col-md-6">
      <!-- START panel-->
      <div class="panel panel-green">
         <div class="panel-heading">
            <div class="row">
               <div class="col-xs-3">
                  <em class="fa fa-cubes fa-5x"></em>
               </div>
               <div class="col-xs-9 text-right">
                  <div class="text-lg"><%= @boardgames_count %></div>
                  <p class="m0">Juegos</p>
               </div>
            </div>
         </div>
         <a href=<%= event_boardgames_path(@event) %> class="panel-footer bg-gray-dark bt0 clearfix btn-block">
            <span class="pull-left">Entrar</span>
            <span class="pull-right">
               <em class="fa fa-chevron-circle-right"></em>
            </span>
         </a>
      </div>
      <!-- END panel-->
   </div>
   <div class="col-lg-3 col-md-6">
      <!-- START panel-->
      <div class="panel panel-green">
         <div class="panel-heading">
            <div class="row">
               <div class="col-xs-3">
                  <em class="fa fa-refresh fa-5x"></em>
               </div>
               <div class="col-xs-9 text-right">
                  <div class="text-lg"><%= @loans_count %></div>
                  <p class="m0">Préstamos</p>
               </div>
            </div>
         </div>
         <a href=<%= event_loans_path(@event) %> class="panel-footer bg-gray-dark bt0 clearfix btn-block">
            <span class="pull-left">Entrar</span>
            <span class="pull-right">
               <em class="fa fa-chevron-circle-right"></em>
            </span>
         </a>
      </div>
      <!-- END panel-->
   </div>
   <div class="col-lg-3 col-md-6">
      <!-- START panel-->
      <div class="panel panel-green">
         <div class="panel-heading">
            <div class="row">
               <div class="col-xs-3">
                  <em class="fa fa-handshake-o fa-5x"></em>
               </div>
               <div class="col-xs-9 text-right">
                  <div class="text-lg"><%= @tournaments_count %></div>
                  <p class="m0">Torneos</p>
               </div>
            </div>
         </div>
         <a href=<%= event_tournaments_path(@event) %> class="panel-footer bg-gray-dark bt0 clearfix btn-block">
            <span class="pull-left">Entrar</span>
            <span class="pull-right">
               <em class="fa fa-chevron-circle-right"></em>
            </span>
         </a>
      </div>
      <!-- END panel-->
   </div>
</div>

<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<!-- START widget-->
		<div class="panel panel-default">
		   <div class="panel-body">
		      <div class="text-center">
		         <h3 class="mt0"><%= @event.name %></h3>
		      </div>
		      <hr>
		      <ul class="list-unstyled ph-xl">
		         <li>
		            <em class="fa fa-map-marker fa-fw mr-lg"></em><%= location(@event.city, @event.province) %>
		         </li>
		         
		      </ul>
		   </div>
		   <table class="table bb">
		   <tbody>
		      <tr>
		         <td>
		            <strong>Comienza</strong>
		         </td>
		         <td><%= beauty_date(@event.start_date) %></td>

		      </tr>
		      <tr>
		         <td>
		            <strong>Finaliza</strong>
		         </td>
		         <td><%= beauty_date(@event.end_date) %></td>
		      </tr>
			</tbody>
			</table>
		</div>
		<!-- END widget-->
	</div>
</div>