config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    scope module: 'event' do
      resources :boardgames, only: [:index, :show, :update, :destroy]
      get "/players/show_by_dni", to: "players#show_by_dni"
      resources :players, except: [:new, :destroy]
      resources :loans, only: [:index, :create, :destroy]

      resources :tournaments, except: [:new] do
        resources :participants, only: [:create, :destroy, :update]
        get :autocomplete_boardgame_name, on: :collection
        get :autocomplete_player_dni, on: :collection
      end
    end
  end

  namespace :admin do
    resources :boardgames
    resources :organizations
    resources :players
    resources :users

    namespace :import do
      resources :bgg_boardgames, only: [:index, :create, :new]
      resources :bgg_collections, only: [:index, :create]
    end
  end

  # defaults to dashboard
  root to: redirect('/events')
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :boardgames, -> { distinct },
                          before_add: :cant_add_boardgame_with_active_loans,
                          before_remove: :cant_del_boardgame_with_active_loans
  has_and_belongs_to_many :players, -> { distinct }
  has_many :loans
  has_many :tournaments
  belongs_to :organization

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :organization, presence: true
  validate  :start_date_cannot_be_after_end_date

  private

  def start_date_cannot_be_after_end_date
    return unless start_date.present? && end_date.present?
    errors.add(:start_date, "can't be after end_date") if start_date > end_date
  end

  def cant_add_boardgame_with_active_loans(boardgame)
    return if boardgame.active_loans.blank?
    errors.add(:boardgame, "boardgame with active loans can't be added")
    raise ActiveRecord::Rollback
  end

  def cant_del_boardgame_with_active_loans(boardgame)
    return unless boardgame.active_loans.at_event(self)
    errors.add(:boardgame, "boardgame with active loans can't be removed")
    raise ActiveRecord::Rollback
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :boardgame, -> { with_deleted }
  belongs_to :event
  has_many :participants, dependent: :destroy

  validates_presence_of :name, :date, :max_competitors, :max_substitutes, :event, :boardgame
  validate :date_must_be_at_event_range

  def max_participants
    max_competitors + max_substitutes
  end

  def max_participants_rearched
    participants.count >= max_participants
  end

  def competitors
    participants.competitors
  end

  def substitutes
    participants.substitutes
  end

  def confirmed
    participants.confirmed
  end

  def league_system(my_teams = confirmed)
    teams             = my_teams.to_a
    rounds            = {}
    rounds[:home]     = []
    rounds[:away]     = []
    number_of_rounds  = teams.length - 1
    number_of_matches = teams.length / 2

    number_of_rounds.times do
      matches_home = []
      matches_away = []

      number_of_matches.times do |index|
        team1 = teams[index]
        team2 = teams[number_of_rounds - index]

        matches_home << [team1, team2]
        matches_away << [team2, team1]
      end

      rounds[:home] << matches_home
      rounds[:away] << matches_away

      # rotate teams
      last = teams.pop
      teams.insert(1, last)
    end

    rounds
  end

  private

  def date_must_be_at_event_range
    return false unless date.present? && event.present?
    if date < event.start_date
      errors.add(:date, "can't be before event start date")
    elsif date > event.end_date
      errors.add(:date, "can't be afer event end date")
    end
  end
end

app/controllers/concerns/events/check_authorized.rb
module Events
  module CheckAuthorized
    extend ActiveSupport::Concern

    included do
      before_action :current_user_belongs_to_organization

      def event_organization
        @event = Event.find(params[:event_id])
        @event.organization
      end

      def current_user_belongs_to_organization
        unless event_organization == current_user.organization || current_user.admin?
          redirect_to root_path, notice: "Access forbidden."
        end
      end
    end
  end
end

app/controllers/event/boardgames_controller.rb
class Event::BoardgamesController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event, :set_organization_boardgames

  def index
    @boardgames_included     = @event.boardgames.order(name: :asc).to_a
    @boardgames_not_included = @boardgames.where.not(id: @boardgames_included).order(name: :asc)
  end

  def show
    @boardgame = @event.boardgames.find_by(id: params[:id])
    @loan      = @boardgame.active_loans.at_event(@event)

    if @loan.present?
      loan_json = {
        id:  @loan[0].id,
        dni: @loan[0].player.dni,
        name: @loan[0].player.name
      }
    end

    respond_to do |format|
      format.html
      format.json do
        render json: {
          attributes: @boardgame,
          loan:       loan_json
        }
      end
    end
  end

  def update
    @boardgame = @boardgames.find_by(id: params[:id])

    if @event.boardgames << @boardgame
      redirect_to event_boardgames_path, notice: "Juego añadido al evento."
    else
      redirect_to event_boardgames_path, alert: @event.errors[:boardgame].to_sentence
    end
  end

  def destroy
    @boardgame = @boardgames.find_by(id: params[:id])
    if @event.boardgames.delete(@boardgame)
      redirect_to event_boardgames_path, notice: "Juego eliminado del evento."
    else
      redirect_to event_boardgames_path, alert: @event.errors[:boardgame].to_sentence
    end
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def set_organization_boardgames
    @boardgames = @event.organization.boardgames
  end
end

app/controllers/event/loans_controller.rb
class Event::LoansController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event

  def index
    @loan  = Loan.new
    @loans = @event.loans.ordered
    keywords = params.fetch(:search, {}).fetch(:keywords, nil)
    @boardgames = search_boardgame_to_borrow_by_keyword(keywords)
  end

  def create
    player = @event.players.find_by(dni: params[:dni])

    if player
      @loan = @event.loans.new(boardgame_id: params[:loan][:boardgame_id], player: player)

      if @loan.save
        redirect_to event_loans_url(@event), notice: 'Loan was successfully created.'
      else
        redirect_to event_loans_url(@event), alert: 'Sorry, loans fails to start.'
      end
    else
      redirect_to event_loans_url(@event), alert: 'Invalid DNI, loans fails to start.'
    end
  end

  def destroy
    @loan = @event.loans.find_by(id: params[:id])

    if @loan.return
      redirect_to event_loans_url(@event), notice: 'Loan was successfully returned.'
    else
      redirect_to event_loans_url(@event), alert: 'Loan fails to return.'
    end
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def search_boardgame_to_borrow_by_keyword(keyword)
    return [] unless keyword.present?

    if keyword.length == 13 && keyword.match(/^\d+$/)
      @event.boardgames.search_by_barcode(keyword)
    elsif keyword.length == 5 && keyword.match(/^[a-zA-Z]{2}\d{3}/)
      @event.boardgames.search_by_internalcode(keyword)
    else
      @event.boardgames.search_by_name(keyword)
    end
  end
end

app/controllers/event/participants_controller.rb
class Event::ParticipantsController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event, :find_tournament

  def create
    player = @event.players.find_by(id: params[:search][:player_id])
    if player
      @participant = @tournament.participants.new(player: player)
      if @participant.save
        flash[:notice] = 'Jugador añadido al torneo.'
      else
        flash[:alert] = @participant.errors.values
      end
    else
      flash[:alert] = 'DNI no válido, no se pudo añadir al jugador al torneo.'
    end

    redirect_to event_tournament_path(@event, @tournament)
  end

  def destroy
    @participant = @tournament.participants.find_by(id: params[:id])

    if @participant.destroy
      flash[:notice] = 'Jugador eliminado del torneo.'
    else
      flash[:alert] = @participant.errors[:participant].to_sentence
    end

    redirect_to event_tournament_path(@event, @tournament)
  end

  def update
    @participant = @tournament.participants.find_by(id: params[:id])
    @participant.toggle_confirmed
    @participant.save

    redirect_to event_tournament_path(@event, @tournament), notice: 'Jugador confirmado.'
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_tournament
    @tournament = @event.tournaments.find_by(id: params[:tournament_id])
  end
end

app/controllers/event/players_controller.rb
class Event::PlayersController < ApplicationController
  include Events::CheckAuthorized

  before_action :find_event
  before_action :set_organization, only: [:show_by_dni, :create, :update]

  def index
    @players = @event.players.all
    @player  = @event.players.new
  end

  def show
    @player = @event.players.find_by(id: params[:id])
  end

  def show_by_dni
    player = @organization.players.find_by(dni: params[:dni].upcase)
    unless player
      render json: { error: "player not found" },
             status: 404
      return
    end
    render json: player
  end

  def edit
    @player = @event.players.find_by(id: params[:id])
  end

  def create
    @players = @event.players.all
    @player  = @event.players.new(player_params)
    @player.organizations.push(@organization)
    if @event.save
      redirect_to [@event, @player], notice: "User was successfully created."
    else
      render :index
    end
  end

  def update
    @player = @event.players.find_by(id: params[:id])
    unless @player
      @player = @organization.players.find_by(id: params[:id])
      @event.players.push(@player)
    end

    if @player.update(player_params)
      redirect_to [@event, @player], notice: "User was successfully included."
    else
      render :edit
    end
  end

  private

  def player_params
    params.require(:player).permit(:dni, :firstname, :lastname, :city, :province, :birthday, :email, :phone)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def set_organization
    @organization = @event.organization
  end
end

app/controllers/event/tournaments_controller.rb
class Event::TournamentsController < ApplicationController
  include Events::CheckAuthorized

  autocomplete :boardgame, :name, full: true, limit: 20, extra_data: [:thumbnail]
  autocomplete :player, :dni, limit: 20, extra_data: [:firstname, :lastname], display_value: :dni_plus_name
  before_action :find_event

  def index
    @tournaments = @event.tournaments.all
    @tournament  = @event.tournaments.new
  end

  def show
    @tournament    = @event.tournaments.find_by(id: params[:id])
    @boardgame     = @tournament.boardgame
    @competitors   = @tournament.competitors
    @substitutes   = @tournament.substitutes
    @confirmed     = @tournament.confirmed
    @league_rounds = @tournament.league_system(@confirmed) if @confirmed.present?
  end

  def create
    @tournaments = @event.tournaments.all
    @tournament  = @event.tournaments.new(tournament_params)

    if @event.save
      redirect_to [@event, @tournament], notice: 'Tournament was successfully created.'
    else
      render :index, alert: 'Sorry, tournament wasnt created.'
    end
  end

  def edit
    @tournament = @event.tournaments.find_by(id: params[:id])
  end

  def update
    @tournament = @event.tournaments.find_by(id: params[:id])

    if @tournament.update(tournament_params)
      redirect_to [@event, @tournament], notice: 'Tournament was successfully updated.'
    else
      render :edit
    end
  end

  private

  def get_autocomplete_items(parameters)
    items = active_record_get_autocomplete_items(parameters)

    if    parameters[:model] == Boardgame then @event.boardgames & items
    elsif parameters[:model] == Player    then @event.players & items
    end
  end

  def tournament_params
    params.require(:tournament).permit(:name, :max_competitors, :max_substitutes, :date, :minage, :boardgame_id, :event)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_organization
  before_action :current_user_is_the_owner, only: [:show, :edit, :update, :destroy]

  def index
    @events = current_user.admin? ? Event.all : @organization.events
  end

  def show
    @event             = Event.find_by(id: params[:id])
    @loans_count       = @event.loans.count
    @boardgames_count  = @event.boardgames.count
    @players_count     = @event.players.count
    @tournaments_count = @event.tournaments.count
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find_by(id: params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.organization = @organization
    if @event.save
      redirect_to @event, notice: "Event was successfully created."
    else
      render :new
    end
  end

  def update
    @event = Event.find_by(id: params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find_by(id: params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :city, :province)
  end

  def set_organization
    @organization = current_user.organization
  end

  def current_user_is_the_owner
    @event = Event.find_by(id: params[:id])
    unless @event.organization == current_user.organization || current_user.admin?
      redirect_to root_path, notice: "Acess forbidden"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def paint_participants(participants, total)
      "#{participants} / #{total}"
  end
end

app/views/event/tournaments/_edit_form.html.erb
<div class="col-sm-12">
<!-- START panel-->
    <div class="panel panel-default">
        <div class="panel-body">

            <%= form_for([@event, @tournament], html: {id: "search-boardgame", class: "form-horizontal"}) do |f| %>
                <% if @tournament.errors.any? %>
                <div class="alert bg-danger-light alert-dismissible fade in">
                    <button type="button" data-dismiss="alert" aria-label="Close" class="close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <div id="error_explanation">
                        <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

                        <ul>
                            <% @tournament.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <% end %>

                <div class="form-group">
                    <%= f.label :nombre, {class: "col-lg-2 control-label"} %>
                    <div class="col-lg-10">
                        <%= f.text_field :name, {class: "form-control js-dni-autocomplete" } %>  
                    </div>
                </div>
                <div class="form-group">
                    <%= f.label :fecha, {class: "col-lg-2 control-label"} %>
                    <div class="col-lg-10">
                        <%= f.datetime_select :date, {class: "form-control"} %>  
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-10 col-lg-offset-2">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <%= f.label :máximo_participantes, {class: "col-lg-7 control-label"} %>
                                <div class="col-lg-5">
                                    <%= f.number_field :max_competitors, {class: "form-control"} %>  
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <%= f.label :máximo_reservas, {class: "col-lg-7 control-label"} %>
                                <div class="col-lg-5">
                                    <%= f.number_field :max_substitutes, {class: "form-control"} %>  
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <%= f.label :edad_minima, {class: "col-lg-7 control-label"} %>
                                <div class="col-lg-5">
                                    <%= f.number_field :minage, {class: "form-control"} %>  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <%= f.button "Guardar cambios", {class: "btn btn-lg btn-primary"} %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/event/tournaments/_form.html.erb
<div class="col-sm-12">
<!-- START panel-->
    <div class="panel panel-default">
        <div class="panel-body">

            <%= form_for([@event, @tournament], html: {id: "search-boardgame", class: "form-horizontal"}) do |f| %>
                <% if @tournament.errors.any? %>
                <div class="alert bg-danger-light alert-dismissible fade in">
                    <button type="button" data-dismiss="alert" aria-label="Close" class="close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <div id="error_explanation">
                        <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

                        <ul>
                            <% @tournament.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <% end %>

                <div class="form-group">
                    <%= f.label :nombre, {class: "col-lg-2 control-label"} %>
                    <div class="col-lg-10">
                        <%= f.text_field :name, {class: "form-control js-dni-autocomplete" } %>  
                    </div>
                </div>
                <div class="form-group">
                    <%= f.label :juego, {class: "col-lg-2 control-label" } %>
                    <div class="col-lg-10">
                    <%= f.hidden_field :boardgame_id, id: 'my_boardgame_id' %>
                        <%= f.autocomplete_field :boardgame, 
                        autocomplete_boardgame_name_event_tournaments_path,
                        id_element: '#my_boardgame_id', 
                        class: "form-control" %>
                    </div>
                </div>
                <div class="form-group">
                    <%= f.label :fecha, {class: "col-lg-2 control-label"} %>
                    <div class="col-lg-10">
                        <%= f.datetime_select :date, {class: "form-control"} %>  
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-10 col-lg-offset-2">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <%= f.label :máximo_participantes, {class: "col-lg-7 control-label"} %>
                                <div class="col-lg-5">
                                    <%= f.number_field :max_competitors, {class: "form-control"} %>  
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <%= f.label :máximo_reservas, {class: "col-lg-7 control-label"} %>
                                <div class="col-lg-5">
                                    <%= f.number_field :max_substitutes, {class: "form-control"} %>  
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <%= f.label :edad_minima, {class: "col-lg-7 control-label"} %>
                                <div class="col-lg-5">
                                    <%= f.number_field :minage, {class: "form-control"} %>  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <%= f.button "Guardar cambios", {class: "btn btn-lg btn-primary"} %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/event/tournaments/_participants_list.html.erb
<div class="panel">
   <div class="panel-heading"></div>
   <div class="table-responsive">
      <table class="table table-bordered table-hover">
         <thead>
            <tr>
               <th>#</th>
               <th>DNI</th>
               <th>Nombre</th>
               <th></th>
            </tr>
         </thead>
         <tbody>
            <% participants.each_with_index do |participant, index| %>
               <tr>
                  <td><%= index+1 %></td>
                  <td><%= participant.player[:dni] %></td>
                  <td><%= participant.player.name %></td>
                  <td>
                     <%= link_to_unless participant.confirmed?, " Confirmar", 
                     event_tournament_participant_path(@event, @tournament, participant), 
                     { class: "btn btn-default bg-gray-light btn-sm fa fa-user-plus", method: :patch } do

                        link_to " Deshacer", 
                        event_tournament_participant_path(@event, @tournament, participant), 
                        { class: "btn btn-default bg-gray-light btn-sm fa fa-user-times", method: :patch }

                     end %>

                     <%= link_to '', 
                     event_tournament_participant_path(@event, @tournament, participant), 
                     { class: "btn btn-danger bg-danger-light btn-sm fa fa-minus pull-right", method: :delete, 
                        data: { 
                           confirm: "Esto eliminará a #{participant.player.name} del torneo, ¿estás seguro?" } } %>
                  </td>
               </tr>
            <% end %>
         </tbody>
      </table>
   </div>
</div>

app/views/event/tournaments/_search_players_form.html.erb
<%= form_for(:search, url: event_tournament_participants_path(@event, @tournament)) do |f| %>

	<div class="col-lg-8 col-lg-offset-2">
		<div class="input-group input-group-lg mt-xl"> 
            <%= f.hidden_field :player_id, id: 'my_player_id' %>
			<%= f.autocomplete_field :player, 
                autocomplete_player_dni_event_tournaments_path,
                'data-auto-focus' => true,
                id_element: '#my_player_id', 
                 class: "form-control", placeholder: "Introduzca DNI del nuevo participante" %>
			<span class="input-group-btn">
				<%= f.button "Añadir", {class: "btn btn-default"} %>
			</span>
		</div>
	</div>
<% end %>

app/views/event/tournaments/_show_league_rounds.html.erb
<% if @league_rounds.present? %>

   <div class="panel widget">
      <div class="panel-heading text-center">
      </div>
      <div class="panel-body text-center">
         <div class="row">
            <h3>Modo Liga</h3>
         <hr>            
         </div>


         <% @league_rounds[:home].each_with_index do |round, index| %>
            <div class="col-lg-4">
               <div class="panel panel-default">
                  <div class="panel-heading"> <h4 class="text-center"">Ronda <%= index + 1%></h4></div>
                  <div class="table-responsive">
                     <table class="table table-striped">
                        <thead>
                           <tr>
                              <th>#</th>
                              <th>Local</th>
                              <th></th>
                              <th>Visitante</th>
                           </tr>
                        </thead>
                        <tbody>
                           <% round.each_with_index do |match, match_index| %>
                              <tr>
                                 <td><%= match_index +1 %></td>
                                 <td><i class="fa fa-user-o"> </i> <%= match[0].player.name %></td>
                                 <td><i class="fa fa-exchange" aria-hidden="true"></i></td>
                                 <td><i class="fa fa-user"> </i> <%= match[1].player.name %></td>
                              </tr>
                           <% end %>
                        </tbody>
                     </table>
                  </div> 
               </div>
            </div>
         <% end %>
         
      </div>
   </div>
<% end %>

app/views/event/tournaments/_tournament_details.html.erb
<div class="col-lg-4">
	<!-- START widget-->
	<div class="panel widget">
		<div class="panel-body">
			<div class="row row-table text-center">
				<div class="col-xs-4">
					<p>Edad</p>
					<h3 class="m0 text-inherit"><%= min_age(@tournament.minage) %></h3>
				</div>
				<div class="col-xs-4">
					<p>Participantes</p>
					<h3 class="m0 text-inherit"><%= paint_participants(@competitors.count, @tournament.max_competitors) %></h3>
				</div>
				<div class="col-xs-4">
					<p>Reservas</p>
					<h3 class="m0 text-inherit"><%= paint_participants(@substitutes.count, @tournament.max_substitutes) %></h3>
				</div>
			</div>
			<hr>
			<div class="row row-table text-center">
				<div class="col-xs-12">
					<p>Fecha</p>
					<h3 class="m0 text-inherit"><%= beauty_date(@tournament.date) %></h3>
				</div>
			</div>
		</div>			
		<%= img_boardgame(@boardgame, "image") %>
	</div>
	<!-- END widget-->
</div>
<div class="col-lg-8">
	<div class="panel widget">
		<div class="panel-heading text-center">
			<div class="row">
				<%= render 'search_players_form' %>
			</div>
		</div>

		<div class="panel-body text-center">
			<div class="row">
				<h3>Participantes</h3>
				<div class="col-sm-12">
					<%= render partial: 'participants_list', locals: { participants: @competitors } %>     
				</div>
			</div>
			<hr>
			<div class="row">
				<h3>Reservas</h3>
				<div class="col-sm-12">
					<%= render partial: 'participants_list', locals: { participants: @substitutes } %>     
				</div>
			</div>
		</div>
	</div>
</div>

app/views/event/tournaments/_tournaments_list.html.erb
<div class="panel">
   <div class="panel-heading"></div>
   <div class="table-responsive">
      <table class="table table-bordered table-hover">
         <thead>
            <tr>
               <th>#</th>
               <th>Portada</th>
               <th>Nombre</th>
               <th>juego</th>
               <th>Fecha</th>
               <th>Participantes</th>
               <th>Lista de espera</th>
               <th>Edad</th>
               <th></th>
            </tr>
         </thead>
         <tbody>

            <% tournaments.each_with_index do |tournament, index| %>
            <tr>
               <td><%= index+1 %></td>
               <td>
                  <div class="media">
                  <%= img_boardgame(tournament.boardgame) %>
                  </div>
               </td>
               <td><%= tournament[:name] %></td>
               <td><%= tournament.boardgame[:name] %></td>
               <td><%= beauty_date(tournament[:date]) %></td>
               <td><%= paint_participants(tournament.competitors.count, tournament[:max_competitors]) %></td>
               <td><%= paint_participants(tournament.substitutes.count, tournament[:max_substitutes]) %></td>
               <td><%= tournament[:minage] %></td>
               <td>
                  <%= link_to 'Mostrar', event_tournament_path(@event, tournament), { class: "btn btn-default btn-sm bg-gray-lighter" } %>
                  <%= link_to '', edit_event_tournament_path(@event, tournament), { class: "btn btn-success bg-success-light btn-sm fa fa-pencil" } %>
               </td>
            </tr>
            <% end %>

         </tbody>
      </table>
   </div>
</div>

app/views/event/tournaments/edit.html.erb
<div class="content-heading">
	Editar torneo <%= @tournament.name %> - Evento <%= @event.name %>
	<%= link_to 'Volver', event_tournaments_path(@event), { class: "mb-lg btn btn-default btn-lg pull-right" } %>
</div>
<div class="row">
	<%= render 'edit_form' %>
</div>

app/views/event/tournaments/index.html.erb
<div class="content-heading">      
   Torneos - <%= @event.name %>
   <%= link_to 'Volver', event_path(@event), { class: "mb-lg btn btn-default btn-lg pull-right" } %>
</div>
<div>
   <div class="panel panel-default">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs nav-justified mb-xl" role="tablist">
         <li role="presentation"><a href="#new" aria-controls="new" role="tab" data-toggle="tab">Nuevo</a></li>
         <li role="presentation" class="active"><a href="#list" aria-controls="list" role="tab" data-toggle="tab">Torneos</a></li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
         <div role="tabpanel" class="tab-pane" id="new">
            <div class="row">
                  <%= render 'form' %>     
            </div>
         </div>
         <div role="tabpanel" class="tab-pane active" id="list">
            <div class="row">
               <div class="col-sm-12">
                  <%= render partial: 'tournaments_list', locals: { tournaments: @tournaments } %>     
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/event/tournaments/show.html.erb
<div class="content-heading">
	Torneo <%= @tournament.name %> - Evento <%= @event.name %>
	<%= link_to 'Volver', event_tournaments_path(@event), { class: "mb-lg btn btn-default btn-lg pull-right" } %>
</div>
<div class="panel panel-default">
      <!-- Nav tabs -->
	<ul class="nav nav-tabs nav-justified" role="tablist">
		<li role="presentation" class="active">
			<a href="#inscriptions" aria-controls="inscriptions" role="tab" data-toggle="tab">Inscripciones</a>
		</li>
		<li role="presentation">
			<a href="#start" aria-controls="start" role="tab" data-toggle="tab">Comenzar Torneo</a>
		</li>
	</ul>
	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="inscriptions">

			<div class="row">
				<%= render 'tournament_details' %>
			</div>

		</div>
		<div role="tabpanel" class="tab-pane" id="start">
			<div class="row">
				<%= render 'show_league_rounds' %>
			</div>
		</div>
	</div>
</div>