config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    scope module: 'event' do
      resources :boardgames, only: [:index, :show, :update, :destroy]
      get "/players/show_by_dni", to: "players#show_by_dni"
      resources :players, except: [:new, :destroy]
      resources :loans, only: [:index, :create, :destroy]

      resources :tournaments, except: [:new] do
        resources :participants, only: [:create, :destroy, :update]
        get :autocomplete_boardgame_name, on: :collection
        get :autocomplete_player_dni, on: :collection
      end
    end
  end

  namespace :admin do
    resources :boardgames
    resources :organizations
    resources :players
    resources :users

    namespace :import do
      resources :bgg_boardgames, only: [:index, :create, :new]
      resources :bgg_collections, only: [:index, :create]
    end
  end

  # defaults to dashboard
  root to: redirect('/events')
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_and_belongs_to_many :players, -> { distinct }
  has_many :events
  has_many :boardgames
  has_many :users

  validates :name, presence: true
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  def index
    @organizations = Organization.page(params[:page])
  end

  def show
    @organization = Organization.find_by(id: params[:id])
  end

  def new
    @organization = Organization.new
  end

  def edit
    @organization = Organization.find_by(id: params[:id])
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to admin_organization_url(@organization), notice: "Organization was successfully created."
    else
      render :new
    end
  end

  def update
    @organization = Organization.find_by(id: params[:id])
    if @organization.update(organization_params)
      redirect_to admin_organization_url(@organization)
    else
      render :edit
    end
  end

  def destroy
    @organization = Organization.find_by(id: params[:id])
    @organization.destroy
    redirect_to admin_organizations_path
  end

  private

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/views/admin/organizations/_form.html.slim
.col-sm-12
  <!-- START panel-->
  .panel.panel-default
    .panel-body
      = form_for([:admin, @organization], html: {class: "form-horizontal"}) do |f|
        - if @organization.errors.any?
          .alert.bg-danger-light.alert-dismissible.fade.in
            span x
            #error_explanation
              h2
                = pluralize(@organization.errors.count, "error")
                prohibited this organization from being saved:
              ul
                - @organization.errors.full_messages.each do |message|
                  li
                    = message
        .form-group
          = f.label :name, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_field :name, class: "form-control"
        .form-group
          .col-lg-offset-2.col-lg-10
            = f.button "Guardar cambios", class: "btn btn-lg btn-primary"

app/views/admin/organizations/edit.html.slim
.content-heading
  Editar
  	= @organization.name
	= link_to 'Volver', :back, class: "mb-lg btn btn-default btn-lg pull-right"
.row
  =render 'form'

app/views/admin/organizations/index.html.slim
.content-heading
  | Organizaciones
  = link_to 'Volver', :back, { class: "mb-lg btn btn-default btn-lg pull-right" }
.row
  .col-sm-12
    .panel
      .panel-heading
      .table-responsive
        table.table.table-bordered.table-hover
          thead
            tr
              th #
              th Nombre
              th
          tbody
            - @organizations.each_with_index do |organization, index|
              tr
                td= index + 1
                td= organization[:name]
                td
                  => link_to 'Mostrar', admin_organization_path(organization), class: "btn btn-sm bt-primary bg-gray-lighter"
                  => link_to '', edit_admin_organization_path(organization), class: "btn btn-success btn-sm bg-success-light fa fa-pencil"
                  => link_to '', admin_organization_path(organization), method: :delete, class: "btn btn-danger btn-sm bg-danger-light fa fa-trash-o"
      = render partial: 'pagination_footer', locals: { elements: @organizations }

app/views/admin/organizations/new.html.slim
.content-heading
  | Nueva organización
.row
  =render 'form'

app/views/admin/organizations/show.html.slim
.content-heading
	= @organization.name
	= link_to 'Volver', :back, class: "mb-lg btn btn-default btn-lg pull-right"
.row
	.col-lg-6.col-lg-offset-3
		<!-- START widget-->
		.panel.panel-default
			.panel-body
				.text-center
					h3.mt0
						= @organization.name
		<!-- END widget-->